spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my-auto
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver
    initialize: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  devtools:
    restart:
      enabled: false
server:
  port: 8099